# Generated by Django 4.2.5 on 2023-11-27 12:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_lifecycle.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_index=True, max_length=36, unique=True)),
                ('max_usages', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(db_index=True, max_length=128, unique=True)),
                ('address', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(db_index=True, max_length=128, unique=True)),
                ('release_date', models.CharField(max_length=16)),
                ('genre', models.CharField(max_length=32)),
                ('showing_from', models.CharField(max_length=32)),
                ('certificate', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('running_time', models.CharField(max_length=16)),
                ('image_1', models.ImageField(upload_to='film_images')),
                ('image_2', models.ImageField(upload_to='film_images')),
                ('copyright', models.TextField(blank=True)),
                ('live', models.BooleanField(default=False)),
                ('sold_out', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_id', models.CharField(blank=True, max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(help_text='Changes will trigger an updated confirmation email', max_length=254)),
                ('quantity', models.IntegerField(help_text='Changes will trigger an updated confirmation email, or cancellation email if set to 0', validators=[django.core.validators.MaxValueValidator(4)])),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('access_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.accesscode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=24, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='qr_code_images')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.film')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.reservation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=128, unique=True)),
                ('starts_at', models.DateTimeField()),
                ('capacity', models.IntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cinema')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.film')),
            ],
            options={
                'ordering': ['cinema__name', 'starts_at'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='screening',
            field=models.ForeignKey(help_text='Changes will trigger an updated confirmation email', on_delete=django.db.models.deletion.PROTECT, to='core.screening'),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='valid_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.film'),
        ),
    ]
